### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by alltonp** [bloodyowl/reason-test-framework#2]
Hi, thank you, this looks like a really nice API for writing reason tests!

I tried to run the example in the README.md and got the following error.

Any ideas how to fix it?

```
 FAIL  __tests__/ReasonTestFrameworkTest.bs.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/user/dev/project/node_modules/reason-test-framework/src/TestFramework.bs.js:3
    import * as Curry from "bs-platform/lib/es6/curry.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      3 | import * as Block from "bs-platform/lib/es6/block.js";
      4 | import * as Curry from "bs-platform/lib/es6/curry.js";
    > 5 | import * as TestFramework from "reason-test-framework/src/TestFramework.bs.js";
        | ^
      6 | 
      7 | Curry._2(TestFramework.describe, "TestFramework", (function (param) {
      8 |         var test = param.test;

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1179:56)
      at Object.<anonymous> (__tests__/ReasonTestFrameworkTest.bs.js:5:1)
```

**Comment by johnridesabike** [comment]
It looks like you're using the `es6` option in your bsconfig.json. Jest does not work with ES6 module syntax out of the box. The easiest way to fix this is to change your configuration to use `commonjs`. If you need to use ES6 modules, you can follow the instructions in the error message to configure Jest to transform the ES6 module syntax.

**Comment by bloodyowl** [comment]
@alltonp I'd recommend switching to [rescript-test](https://github.com/bloodyowl/rescript-test) if you want a lighter solution that works natively with ES6 modules.

If you want reason-test-framework, install `babel-jest`, `babel-plugin-dynamic-import-node` and add a `babel.config.js` file like the following:

```js
module.exports = {
  plugins: ["babel-plugin-dynamic-import-node"],
  presets: ["@babel/preset-env"],
}
```
